export const testProducts = [
  {
    id: "p-fruit-apple",
    name: "Apple",
    skuOrBarcode: "APPLE",
    categoryId: "cat-fruit",
    unit: "kg",
    price: 10,
    reorderLevel: 5,
    isActive: true,
    onHand: 20,
    status: "OK",
  },
  {
    id: "p-fruit-apricot",
    name: "Apricot",
    skuOrBarcode: "APR",
    categoryId: "cat-fruit",
    unit: "kg",
    price: 12,
    reorderLevel: 5,
    isActive: true,
    onHand: 3,
    status: "LOW",
  },
  {
    id: "p-veg-broccoli",
    name: "Broccoli",
    skuOrBarcode: "BROC",
    categoryId: "cat-veg",
    unit: "kg",
    price: 8,
    reorderLevel: 10,
    isActive: true,
    onHand: 0,
    status: "OUT",
  },
  {
    id: "p-dairy-milk",
    name: "Milk",
    skuOrBarcode: undefined,
    categoryId: "cat-dairy",
    unit: "ltr",
    price: 5,
    reorderLevel: 2,
    isActive: true,
    onHand: 50,
    status: "OK",
  },
  {
    id: "p-tools-hammer",
    name: "Hammer",
    skuOrBarcode: "123456",
    categoryId: "cat-tools",
    unit: "pcs",
    price: 25,
    reorderLevel: 5,
    isActive: false,
    onHand: 0,
    status: "OUT",
  },
];
